FROM ubuntu:22.04
RUN apt-get update
RUN apt-get install -y nodejs npm curl wget git python3
COPY . /app
WORKDIR /app
RUN npm install
EXPOSE 3000
CMD ["node", "src/index.js"]

# # Construire l'image "mauvaise"
# docker build -f app/Dockerfile.bad -t app:bad app/

# # Vérifier la taille
# docker images app:bad
# # → probablement > 500 MB !